apiVersion: apps/v1
kind: Deployment
metadata:
  name: kube-quu-app
spec:
  replicas: 3
  selector:
    matchLabels:
      app: kube-quu-app
  template:
    metadata:
      labels:
        app: kube-quu-app
    spec:
      containers:
        - name: kube-quu-app
          image: liar233/service_quu:0.0.1
          ports:
            - containerPort: 80
              protocol: TCP